#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "drv_fpioa.h"
#include "drv_gpio.h"
#include "drv_pufs.h"
#include "otp_provision_board.h"

#define OTP_BASE_SIZE              1024U
#define OTP_WORD_SIZE              4U
#define KDIMG_HDR_MAGIC            0x27CB8F93U
#define KDIMG_PART_MAGIC           0x91DF6DA4U
#define KDIMG_HEADER_SIZE          512U
#define KDIMG_PART_ENTRY_SIZE      256U
#define KDIMG_EXPECTED_PART_COUNT  2U
#define KDIMG_LOCK_PART_OFFSET     OTP_BASE_SIZE
#define OTP_LOCK_RO_FLAG           0x12345678U
#define OTP_LOCK_NA_FLAG           0xDEADBEEFU
#define OTP_STATUS_LED_DRYRUN_BLINKS 2U
#define OTP_STATUS_LED_FAIL_BLINKS   3U
#define OTP_STATUS_LED_BLINK_DELAY_US 200000U
#define OTP_STATUS_LED_PATTERN_GAP_US (OTP_STATUS_LED_BLINK_DELAY_US * 3U)

typedef struct __attribute__((packed)) {
    uint32_t img_hdr_magic;
    uint32_t img_hdr_crc32;
    uint32_t img_hdr_flag;
    uint32_t img_hdr_version;
    uint32_t part_tbl_num;
    uint32_t part_tbl_crc32;
    char     image_info[32];
    char     chip_info[32];
    char     board_info[64];
    uint8_t  reserved[KDIMG_HEADER_SIZE - 152U];
} kdimg_hdr_t;

typedef struct __attribute__((packed)) {
    uint32_t part_magic;
    uint32_t part_offset;
    uint32_t part_size;
    uint32_t part_erase_size;
    uint32_t part_max_size;
    uint32_t reserved0;
    uint64_t part_flag;
    uint32_t part_content_offset;
    uint32_t part_content_size;
    uint8_t  part_content_sha256[32];
    char     part_name[32];
    uint8_t  reserved[KDIMG_PART_ENTRY_SIZE - 104U];
} kdimg_part_t;

typedef struct {
    const uint8_t *data_bytes;
    size_t         data_size;
    const uint8_t *lock_bytes;
    size_t         lock_size;
    const char    *format_name;
} otp_payload_t;

typedef enum {
    OTP_OUTCOME_NONE = 0,
    OTP_OUTCOME_SUCCESS,
    OTP_OUTCOME_DRY_RUN,
    OTP_OUTCOME_FAILURE,
} otp_outcome_t;

static void print_usage(const char *prog)
{
    printf("Usage: %s <input-file> [--yes] [--skip-verify]\n", prog);
    printf("\n");
    printf("Supported input formats:\n");
    printf("  - raw OTP binary exactly 1024 bytes, written to base OTP addresses 0x000-0x3ff\n");
    printf("  - two-part otp_full.kdimg generated by tools/gen_otp_config.py\n");
    printf("\n");
    printf("Notes:\n");
    printf("  - OTP programming is irreversible. Inspect the payload before using --yes.\n");
    printf("  - If RT_PUFS_OTP_WRITE_ENABLE is disabled, the driver only performs a dry-run.\n");
    printf("  - The input format is detected from file content, not file extension.\n");
    printf("  - For otp_full.kdimg, this sample requires exactly two parts and writes\n");
    printf("    the otp_data part to 0x000-0x3ff\n");
    printf("    and converts the otp_key_lock part into drv_pufs_otp_lock calls.\n");
    printf("  - After --yes, GPIO%d is used as a status LED by default (override OTP_STATUS_LED_PIN at build time).\n",
           OTP_STATUS_LED_PIN);
}

static const char *otp_outcome_name(otp_outcome_t outcome)
{
    switch (outcome) {
    case OTP_OUTCOME_SUCCESS:
        return "success";
    case OTP_OUTCOME_DRY_RUN:
        return "dry-run";
    case OTP_OUTCOME_FAILURE:
        return "failure";
    default:
        return "none";
    }
}

static gpio_pin_value_t otp_status_led_value(bool on)
{
#if OTP_STATUS_LED_ACTIVE_LOW
    return on ? GPIO_PV_LOW : GPIO_PV_HIGH;
#else
    return on ? GPIO_PV_HIGH : GPIO_PV_LOW;
#endif
}

static int otp_status_led_prepare(drv_gpio_inst_t **led)
{
    if (!led) {
        errno = EINVAL;
        return -1;
    }

    if (OTP_STATUS_LED_PIN < 0) {
        errno = ENODEV;
        return -1;
    }

    if (drv_fpioa_set_pin_func(OTP_STATUS_LED_PIN, (fpioa_func_t)(GPIO0 + OTP_STATUS_LED_PIN)) != 0) {
        return -1;
    }

    if (drv_gpio_inst_create(OTP_STATUS_LED_PIN, led) != 0) {
        return -1;
    }

    if (drv_gpio_mode_set(*led, GPIO_DM_OUTPUT) != 0) {
        drv_gpio_inst_destroy(led);
        return -1;
    }

    if (drv_gpio_value_set(*led, otp_status_led_value(false)) != 0) {
        drv_gpio_inst_destroy(led);
        return -1;
    }

    return 0;
}

static void otp_status_led_blink(drv_gpio_inst_t *led, unsigned int delay_us)
{
    if (!led) {
        return;
    }

    drv_gpio_value_set(led, otp_status_led_value(true));
    usleep(delay_us);
    drv_gpio_value_set(led, otp_status_led_value(false));
    usleep(delay_us);
}

static void otp_status_led_blink_group(drv_gpio_inst_t *led, size_t count, unsigned int delay_us)
{
    if (!led || count == 0U) {
        return;
    }

    for (size_t index = 0; index < count; ++index) {
        otp_status_led_blink(led, delay_us);
    }

    usleep(OTP_STATUS_LED_PATTERN_GAP_US);
}

static void otp_status_led_loop(drv_gpio_inst_t *led, otp_outcome_t outcome)
{
    if (!led) {
        return;
    }

    switch (outcome) {
    case OTP_OUTCOME_SUCCESS:
        while (1) {
            otp_status_led_blink_group(led, 1U, OTP_STATUS_LED_BLINK_DELAY_US);
        }
        break;
    case OTP_OUTCOME_DRY_RUN:
        while (1) {
            otp_status_led_blink_group(led, OTP_STATUS_LED_DRYRUN_BLINKS, OTP_STATUS_LED_BLINK_DELAY_US);
        }
        break;
    case OTP_OUTCOME_FAILURE:
        while (1) {
            otp_status_led_blink_group(led, OTP_STATUS_LED_FAIL_BLINKS, OTP_STATUS_LED_BLINK_DELAY_US / 2U);
        }
        break;
    default:
        break;
    }
}

static void otp_status_led_signal(otp_outcome_t outcome)
{
    drv_gpio_inst_t *led = NULL;

    if (outcome == OTP_OUTCOME_NONE || OTP_STATUS_LED_PIN < 0) {
        return;
    }

    if (otp_status_led_prepare(&led) != 0) {
        fprintf(stderr,
                "[otp_provision] Warning: failed to drive status LED on GPIO%d\n",
                OTP_STATUS_LED_PIN);
        return;
    }

    fprintf(stderr, "[otp_provision] LED status loop active, press Ctrl+C to stop.\n");
    otp_status_led_loop(led, outcome);

    drv_gpio_inst_destroy(&led);
}

static int read_full(int fd, uint8_t *buffer, size_t size)
{
    size_t total = 0;

    while (total < size) {
        ssize_t ret = read(fd, buffer + total, size - total);

        if (ret < 0) {
            if (errno == EINTR) {
                continue;
            }

            return -1;
        }

        if (ret == 0) {
            errno = EIO;
            return -1;
        }

        total += (size_t)ret;
    }

    return 0;
}

static int load_file(const char *path, uint8_t **buffer, size_t *size)
{
    struct stat st;
    int         fd;
    uint8_t    *data;

    if (!path || !buffer || !size) {
        errno = EINVAL;
        return -1;
    }

    if (stat(path, &st) != 0) {
        return -1;
    }

    if (st.st_size <= 0) {
        errno = EINVAL;
        return -1;
    }

    data = (uint8_t *)malloc((size_t)st.st_size);
    if (!data) {
        errno = ENOMEM;
        return -1;
    }

    fd = open(path, O_RDONLY);
    if (fd < 0) {
        free(data);
        return -1;
    }

    if (read_full(fd, data, (size_t)st.st_size) != 0) {
        int saved_errno = errno;

        close(fd);
        free(data);
        errno = saved_errno;
        return -1;
    }

    close(fd);

    *buffer = data;
    *size   = (size_t)st.st_size;
    return 0;
}

static uint32_t read_le32(const uint8_t *bytes)
{
    return ((uint32_t)bytes[0]) |
           ((uint32_t)bytes[1] << 8) |
           ((uint32_t)bytes[2] << 16) |
           ((uint32_t)bytes[3] << 24);
}

static const char *otp_lock_state_name(uint8_t lock_state);

static int decode_lock_word(const uint8_t *bytes, uint8_t *lock_state, bool *has_request)
{
    uint32_t word;

    if (!bytes || !lock_state || !has_request) {
        errno = EINVAL;
        return -1;
    }

    word = read_le32(bytes);
    if (word == 0U) {
        *has_request = false;
        *lock_state = OTP_SKIP;
        return 0;
    }

    if (word == OTP_LOCK_RO_FLAG) {
        *has_request = true;
        *lock_state = OTP_RO;
        return 0;
    }

    if (word == OTP_LOCK_NA_FLAG) {
        *has_request = true;
        *lock_state = OTP_NA;
        return 0;
    }

    fprintf(stderr,
            "[otp_provision] Unsupported lock word 0x%08x in otp_key_lock payload\n",
            (unsigned int)word);
    return -1;
}

static int summarize_lock_requests(const uint8_t *lock_bytes,
                                   size_t lock_size,
                                   size_t *request_words,
                                   size_t *request_regions)
{
    uint8_t previous_lock = OTP_SKIP;
    bool    previous_pending = false;

    if (!request_words || !request_regions) {
        errno = EINVAL;
        return -1;
    }

    *request_words = 0;
    *request_regions = 0;

    if (!lock_bytes || lock_size == 0) {
        return 0;
    }

    if ((lock_size % OTP_WORD_SIZE) != 0U || lock_size > OTP_BASE_SIZE) {
        fprintf(stderr, "[otp_provision] Invalid otp_key_lock payload size %zu\n", lock_size);
        return -1;
    }

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t lock_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &lock_state, &has_request) != 0) {
            return -1;
        }

        if (!has_request) {
            previous_pending = false;
            previous_lock = OTP_SKIP;
            continue;
        }

        (*request_words)++;
        if (!previous_pending || previous_lock != lock_state) {
            (*request_regions)++;
        }

        previous_pending = true;
        previous_lock = lock_state;
    }

    return 0;
}

static int snapshot_requested_lock_states(drv_pufs_inst *dev,
                                          const uint8_t *lock_bytes,
                                          size_t lock_size,
                                          uint8_t *states)
{
    if (!dev || !states) {
        errno = EINVAL;
        return -1;
    }

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t lock_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &lock_state, &has_request) != 0) {
            return -1;
        }

        if (!has_request) {
            states[offset / OTP_WORD_SIZE] = OTP_SKIP;
            continue;
        }

        if (drv_pufs_otp_get_rwlck(dev, (uint16_t)offset, &states[offset / OTP_WORD_SIZE]) != 0) {
            fprintf(stderr, "[otp_provision] Failed to query lock state at 0x%03zx\n", offset);
            return -1;
        }
    }

    return 0;
}

static bool lock_transition_needs_write(uint8_t current_state, uint8_t requested_state)
{
    return (requested_state != OTP_SKIP && current_state != requested_state);
}

static int validate_lock_requests(const uint8_t *lock_bytes,
                                  size_t lock_size,
                                  const uint8_t *states_before)
{
    if (!lock_bytes || !states_before) {
        errno = EINVAL;
        return -1;
    }

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t requested_state;
        uint8_t current_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &requested_state, &has_request) != 0) {
            return -1;
        }

        if (!has_request) {
            continue;
        }

        current_state = states_before[offset / OTP_WORD_SIZE];
        if (!lock_transition_needs_write(current_state, requested_state)) {
            continue;
        }

        if (current_state == OTP_RW) {
            continue;
        }

        if (current_state == OTP_RO && requested_state == OTP_NA) {
            continue;
        }

        fprintf(stderr,
                "[otp_provision] Can't lock %s to %s at 0x%03zx\n",
                otp_lock_state_name(current_state),
                otp_lock_state_name(requested_state),
                offset);
        return -1;
    }

    return 0;
}

static size_t count_pending_lock_words(const uint8_t *lock_bytes,
                                       size_t lock_size,
                                       const uint8_t *states,
                                       size_t *pending_regions)
{
    size_t  pending_words = 0;
    uint8_t previous_lock = OTP_SKIP;
    bool    previous_pending = false;

    if (pending_regions) {
        *pending_regions = 0;
    }

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t lock_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &lock_state, &has_request) != 0) {
            return 0;
        }

        if (!has_request || !lock_transition_needs_write(states[offset / OTP_WORD_SIZE], lock_state)) {
            previous_pending = false;
            previous_lock = OTP_SKIP;
            continue;
        }

        pending_words++;
        if (pending_regions && (!previous_pending || previous_lock != lock_state)) {
            (*pending_regions)++;
        }

        previous_pending = true;
        previous_lock = lock_state;
    }

    return pending_words;
}

static int verify_requested_locks(const uint8_t *lock_bytes,
                                  size_t lock_size,
                                  const uint8_t *states,
                                  size_t *mismatch_words)
{
    size_t pending_regions = 0;
    size_t pending_words;

    pending_words = count_pending_lock_words(lock_bytes, lock_size, states, &pending_regions);
    if (mismatch_words) {
        *mismatch_words = pending_words;
    }

    return (pending_words == 0U) ? 0 : -1;
}

static int apply_lock_requests(drv_pufs_inst *dev,
                               const uint8_t *lock_bytes,
                               size_t lock_size,
                               const uint8_t *states_before)
{
    if (!dev || !lock_bytes || !states_before) {
        errno = EINVAL;
        return -1;
    }

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t requested_state;
        uint8_t current_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &requested_state, &has_request) != 0) {
            return -1;
        }

        if (!has_request) {
            continue;
        }

        current_state = states_before[offset / OTP_WORD_SIZE];
        if (!lock_transition_needs_write(current_state, requested_state)) {
            continue;
        }

        if (current_state == OTP_RO && requested_state == OTP_NA) {
            if (drv_pufs_otp_lock(dev, (uint16_t)offset, OTP_WORD_SIZE, requested_state) != 0) {
                fprintf(stderr, "[otp_provision] Failed to apply lock NA at 0x%03zx\n", offset);
                return -1;
            }

            continue;
        }

        if (current_state != OTP_RW) {
            fprintf(stderr,
                    "[otp_provision] Can't lock %s to %s at 0x%03zx\n",
                    otp_lock_state_name(current_state),
                    otp_lock_state_name(requested_state),
                    offset);
            return -1;
        }

        if (drv_pufs_otp_lock(dev, (uint16_t)offset, OTP_WORD_SIZE, requested_state) != 0) {
            fprintf(stderr,
                    "[otp_provision] Failed to apply lock %s at 0x%03zx\n",
                    otp_lock_state_name(requested_state),
                    offset);
            return -1;
        }
    }

    return 0;
}

static int parse_kdimg_full_payload(const uint8_t *file_bytes, size_t file_size, otp_payload_t *payload)
{
    const kdimg_hdr_t  *hdr;
    const kdimg_part_t *parts;
    bool                have_data = false;
    bool                have_lock = false;

    if (!file_bytes || !payload || file_size < (KDIMG_HEADER_SIZE + KDIMG_EXPECTED_PART_COUNT * KDIMG_PART_ENTRY_SIZE)) {
        return -1;
    }

    hdr = (const kdimg_hdr_t *)file_bytes;
    if (hdr->img_hdr_magic != KDIMG_HDR_MAGIC) {
        return -1;
    }

    if (hdr->part_tbl_num != KDIMG_EXPECTED_PART_COUNT) {
        fprintf(stderr,
                "[otp_provision] Unsupported kdimg part count %u. Expected otp_full.kdimg with 2 parts.\n",
                (unsigned int)hdr->part_tbl_num);
        return -1;
    }

    if ((size_t)hdr->part_tbl_num > ((file_size - KDIMG_HEADER_SIZE) / KDIMG_PART_ENTRY_SIZE)) {
        fprintf(stderr, "[otp_provision] kdimg part table exceeds file size\n");
        return -1;
    }

    parts = (const kdimg_part_t *)(file_bytes + KDIMG_HEADER_SIZE);
    for (uint32_t index = 0; index < hdr->part_tbl_num; ++index) {
        const kdimg_part_t *part = &parts[index];
        char                part_name[33];

        if (part->part_magic != KDIMG_PART_MAGIC) {
            fprintf(stderr, "[otp_provision] Invalid kdimg part magic at index %u\n", (unsigned int)index);
            return -1;
        }

        if ((uint64_t)part->part_content_offset + (uint64_t)part->part_content_size > (uint64_t)file_size) {
            fprintf(stderr, "[otp_provision] kdimg part %u exceeds file size\n", (unsigned int)index);
            return -1;
        }

        memcpy(part_name, part->part_name, sizeof(part->part_name));
        part_name[sizeof(part_name) - 1] = '\0';

        if (strncmp(part_name, "otp_data", sizeof(part->part_name)) == 0) {
            if (part->part_offset != 0U || part->part_content_size != OTP_BASE_SIZE) {
                fprintf(stderr,
                        "[otp_provision] Invalid otp_data part: offset=0x%03x size=%u\n",
                        (unsigned int)part->part_offset,
                        (unsigned int)part->part_content_size);
                return -1;
            }
            payload->data_bytes = file_bytes + part->part_content_offset;
            payload->data_size = part->part_content_size;
            have_data = true;
            continue;
        }

        if (strncmp(part_name, "otp_key_lock", sizeof(part->part_name)) == 0) {
            if (part->part_offset != KDIMG_LOCK_PART_OFFSET || part->part_content_size != OTP_BASE_SIZE) {
                fprintf(stderr,
                        "[otp_provision] Invalid otp_key_lock part: offset=0x%03x size=%u\n",
                        (unsigned int)part->part_offset,
                        (unsigned int)part->part_content_size);
                return -1;
            }
            payload->lock_bytes = file_bytes + part->part_content_offset;
            payload->lock_size = part->part_content_size;
            have_lock = true;
            continue;
        }

        fprintf(stderr,
                "[otp_provision] Unsupported kdimg part '%s'. Expected otp_data and otp_key_lock.\n",
                part_name);
        return -1;
    }

    if (!have_data || !have_lock) {
        fprintf(stderr, "[otp_provision] otp_full.kdimg must contain both otp_data and otp_key_lock\n");
        return -1;
    }

    payload->format_name = "otp_full.kdimg";
    return 0;
}

static int resolve_input_payload(const uint8_t *file_bytes, size_t file_size, otp_payload_t *payload)
{
    if (!file_bytes || !payload || file_size == 0) {
        errno = EINVAL;
        return -1;
    }

    memset(payload, 0, sizeof(*payload));

    if (file_size >= sizeof(uint32_t) && read_le32(file_bytes) == KDIMG_HDR_MAGIC) {
        return parse_kdimg_full_payload(file_bytes, file_size, payload);
    }

    if (parse_kdimg_full_payload(file_bytes, file_size, payload) == 0) {
        return 0;
    }

    if (file_size != OTP_BASE_SIZE) {
        fprintf(stderr,
                "[otp_provision] Raw OTP binary must be exactly %u bytes, got %zu\n",
                OTP_BASE_SIZE,
                file_size);
        return -1;
    }

    payload->data_bytes = file_bytes;
    payload->data_size = file_size;
    payload->lock_bytes = NULL;
    payload->lock_size = 0;
    payload->format_name = "raw otp.bin";
    return 0;
}

static int check_data_word(uint32_t old_data, uint32_t new_data)
{
    return ((old_data & ~new_data) != 0U) ? 1 : 0;
}

static bool data_word_should_write(const uint8_t *current,
                                   const uint8_t *target,
                                   size_t offset,
                                   size_t size)
{
    uint32_t old_data;
    uint32_t new_data;

    if (!current || !target || (offset + OTP_WORD_SIZE) > size) {
        return false;
    }

    old_data = read_le32(current + offset);
    new_data = read_le32(target + offset);

    return (new_data != 0U && old_data == 0U);
}

static int validate_data_words(const uint8_t *current,
                               const uint8_t *target,
                               size_t size)
{
    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        uint32_t old_data;
        uint32_t new_data;

        old_data = read_le32(current + offset);
        new_data = read_le32(target + offset);

        if (new_data == 0U || new_data == old_data) {
            continue;
        }

        if (check_data_word(old_data, new_data) != 0) {
            fprintf(stderr,
                    "[otp_provision] otp can not write 0x%08x to 0x%08x at 0x%03zx\n",
                    (unsigned int)old_data,
                    (unsigned int)new_data,
                    offset);
            return -1;
        }

        if (old_data != 0U) {
            fprintf(stderr,
                    "[otp_provision] otp can write 0x%08x to 0x%08x at 0x%03zx, but now we don't do this\n",
                    (unsigned int)old_data,
                    (unsigned int)new_data,
                    offset);
            return -1;
        }
    }

    return 0;
}

static const char *otp_lock_state_name(uint8_t lock_state)
{
    switch (lock_state) {
    case OTP_NA:
        return "NA";
    case OTP_RO:
        return "RO";
    case OTP_RW:
        return "RW";
    case OTP_SKIP:
        return "SKIP";
    default:
        return "?";
    }
}

static size_t count_changed_program_bytes(const uint8_t *current, const uint8_t *target, size_t size)
{
    size_t changed = 0;

    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        size_t end = offset + OTP_WORD_SIZE;

        if (!data_word_should_write(current, target, offset, size)) {
            continue;
        }

        if (end > size) {
            end = size;
        }

        for (size_t index = offset; index < end; ++index) {
            if (current[index] != target[index]) {
                changed++;
            }
        }
    }

    return changed;
}

static int check_programmable_transition(const uint8_t *current,
                                         const uint8_t *target,
                                         size_t size,
                                         size_t *bad_offset)
{
    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        size_t end = offset + OTP_WORD_SIZE;

        if (!data_word_should_write(current, target, offset, size)) {
            continue;
        }

        if (end > size) {
            end = size;
        }

        for (size_t index = offset; index < end; ++index) {
            if ((current[index] & (uint8_t)(~target[index])) != 0U) {
                if (bad_offset) {
                    *bad_offset = index;
                }
                return -1;
            }
        }
    }

    return 0;
}

static int verify_programmed_bytes(const uint8_t *current,
                                   const uint8_t *before,
                                   const uint8_t *target,
                                   size_t size,
                                   bool *unchanged)
{
    if (unchanged) {
        *unchanged = true;
    }

    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        size_t end = offset + OTP_WORD_SIZE;

        if (!data_word_should_write(before, target, offset, size)) {
            continue;
        }

        if (end > size) {
            end = size;
        }

        for (size_t index = offset; index < end; ++index) {
            if (current[index] != target[index]) {
                if (unchanged && current[index] != before[index]) {
                    *unchanged = false;
                }
                return -1;
            }

            if (unchanged && current[index] != before[index]) {
                *unchanged = false;
            }
        }
    }

    return 0;
}

static void dump_program_data_preview(const uint8_t *current,
                                      const uint8_t *target,
                                      size_t size)
{
    size_t changed_words = 0;

    if (!current || !target) {
        return;
    }

    printf("[otp_provision] Data words to program:\n");

    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        size_t end = offset + OTP_WORD_SIZE;
        bool   word_changed = false;

        if (!data_word_should_write(current, target, offset, size)) {
            continue;
        }

        if (end > size) {
            end = size;
        }

        for (size_t index = offset; index < end; ++index) {
            if (current[index] != target[index]) {
                word_changed = true;
                break;
            }
        }

        if (!word_changed) {
            continue;
        }

        changed_words++;
        printf("  0x%03zx: cur=", offset);
        for (size_t index = offset; index < end; ++index) {
            printf("%02x", current[index]);
            if ((index + 1) < end) {
                printf(" ");
            }
        }

        printf(" -> new=");
        for (size_t index = offset; index < end; ++index) {
            printf("%02x", target[index]);
            if ((index + 1) < end) {
                printf(" ");
            }
        }
        printf("\n");
    }

    if (changed_words == 0) {
        printf("  (none)\n");
    }
}

static void dump_lock_request_preview(const uint8_t *lock_bytes,
                                      size_t lock_size,
                                      const uint8_t *states_before)
{
    size_t pending_words = 0;

    if (!lock_bytes || !states_before) {
        return;
    }

    printf("[otp_provision] Lock words to apply:\n");

    for (size_t offset = 0; offset < lock_size; offset += OTP_WORD_SIZE) {
        uint8_t requested_state;
        uint8_t current_state;
        bool    has_request;

        if (decode_lock_word(lock_bytes + offset, &requested_state, &has_request) != 0) {
            return;
        }

        if (!has_request) {
            continue;
        }

        current_state = states_before[offset / OTP_WORD_SIZE];
        if (!lock_transition_needs_write(current_state, requested_state)) {
            continue;
        }

        pending_words++;
        printf("  0x%03zx: cur=%s -> new=%s\n",
               offset,
               otp_lock_state_name(current_state),
               otp_lock_state_name(requested_state));
    }

    if (pending_words == 0) {
        printf("  (none)\n");
    }
}

static int apply_program_data(drv_pufs_inst *dev,
                              const uint8_t *current,
                              const uint8_t *target,
                              size_t size,
                              size_t *written_words)
{
    size_t applied = 0;

    if (!dev || !current || !target) {
        errno = EINVAL;
        return -1;
    }

    for (size_t offset = 0; offset < size; offset += OTP_WORD_SIZE) {
        uint8_t lock_state = OTP_SKIP;

        if (!data_word_should_write(current, target, offset, size)) {
            continue;
        }

        if (drv_pufs_otp_write(dev, (uint16_t)offset, target + offset, OTP_WORD_SIZE) != 0) {
            if (drv_pufs_otp_get_rwlck(dev, (uint16_t)offset, &lock_state) == 0 && lock_state != OTP_RW) {
                fprintf(stderr,
                        "[otp_provision] OTP write denied at 0x%03zx locked (%s)\n",
                        offset,
                        otp_lock_state_name(lock_state));
            } else {
                fprintf(stderr, "[otp_provision] OTP write request failed at 0x%03zx\n", offset);
            }
            return -1;
        }

        applied++;
    }

    if (written_words) {
        *written_words = applied;
    }

    return 0;
}

int main(int argc, char *argv[])
{
    const char   *input_path   = NULL;
    bool          commit_write = false;
    bool          skip_verify  = false;
    uint8_t      *file_bytes   = NULL;
    size_t        file_size    = 0;
    otp_payload_t payload;
    drv_pufs_inst dev;
    uint8_t      *current      = NULL;
    uint8_t      *verify       = NULL;
    uint8_t      *lock_before  = NULL;
    uint8_t      *lock_after   = NULL;
    size_t        bad_offset   = 0;
    size_t        changed      = 0;
    size_t        lock_words   = 0;
    size_t        lock_regions = 0;
    size_t        pending_lock_words = 0;
    size_t        pending_lock_regions = 0;
    size_t        lock_mismatch_words = 0;
    size_t        written_words = 0;
    bool          data_dry_run = false;
    bool          lock_dry_run = false;
    otp_outcome_t outcome      = OTP_OUTCOME_FAILURE;
    int           ret          = 1;

    memset(&payload, 0, sizeof(payload));
    memset(&dev, 0, sizeof(dev));
    dev.fd = -1;

    for (int index = 1; index < argc; ++index) {
        const char *arg = argv[index];

        if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
            print_usage(argv[0]);
            return 0;
        }

        if (strcmp(arg, "--yes") == 0) {
            commit_write = true;
            continue;
        }

        if (strcmp(arg, "--skip-verify") == 0) {
            skip_verify = true;
            continue;
        }

        if (!input_path && arg[0] != '-') {
            input_path = arg;
            continue;
        }

        if (arg[0] != '-') {
            fprintf(stderr, "[otp_provision] Only one input file is supported: %s\n", arg);
        } else {
            fprintf(stderr, "[otp_provision] Unknown argument: %s\n", arg);
        }
        print_usage(argv[0]);
        return 1;
    }

    if (!input_path) {
        print_usage(argv[0]);
        return 1;
    }

    if (load_file(input_path, &file_bytes, &file_size) != 0) {
        perror("[otp_provision] Failed to read input file");
        goto out;
    }

    if (resolve_input_payload(file_bytes, file_size, &payload) != 0) {
        goto out;
    }

    printf("[otp_provision] Input:  %s\n", input_path);
    printf("[otp_provision] Format: %s\n", payload.format_name);
    printf("[otp_provision] Data:   0x000 - 0x%03x (%zu bytes)\n",
           (unsigned int)(payload.data_size - 1),
           payload.data_size);
    if (payload.lock_bytes && payload.lock_size > 0) {
        printf("[otp_provision] Locks:  otp_key_lock payload present (%zu bytes)\n", payload.lock_size);
    }
    printf("[otp_provision] Warning: base OTP programming is irreversible.\n");

    current = (uint8_t *)malloc(payload.data_size);
    verify  = (uint8_t *)malloc(payload.data_size);
    if (!current || !verify) {
        fprintf(stderr, "[otp_provision] Out of memory\n");
        goto out;
    }

    if (summarize_lock_requests(payload.lock_bytes, payload.lock_size, &lock_words, &lock_regions) != 0) {
        goto out;
    }

    if (payload.lock_bytes && payload.lock_size > 0) {
        lock_before = (uint8_t *)malloc(payload.lock_size / OTP_WORD_SIZE);
        lock_after = (uint8_t *)malloc(payload.lock_size / OTP_WORD_SIZE);
        if (!lock_before || !lock_after) {
            fprintf(stderr, "[otp_provision] Out of memory for lock state tracking\n");
            goto out;
        }
    }

    if (drv_pufs_open(&dev) != 0) {
        fprintf(stderr, "[otp_provision] Failed to open /dev/pufs\n");
        goto out;
    }

    if (drv_pufs_otp_read(&dev, 0, current, payload.data_size) != 0) {
        fprintf(stderr, "[otp_provision] Failed to read current OTP contents\n");
        goto out;
    }

    if (lock_before && snapshot_requested_lock_states(&dev, payload.lock_bytes, payload.lock_size, lock_before) != 0) {
        goto out;
    }

    if (lock_before && validate_lock_requests(payload.lock_bytes, payload.lock_size, lock_before) != 0) {
        goto out;
    }

    if (validate_data_words(current, payload.data_bytes, payload.data_size) != 0) {
        goto out;
    }

    changed = count_changed_program_bytes(current, payload.data_bytes, payload.data_size);
    printf("[otp_provision] Changed bytes: %zu\n", changed);
    if (changed > 0) {
        dump_program_data_preview(current, payload.data_bytes, payload.data_size);
    }
    if (lock_words > 0) {
        pending_lock_words = count_pending_lock_words(payload.lock_bytes,
                                                      payload.lock_size,
                                                      lock_before,
                                                      &pending_lock_regions);
        printf("[otp_provision] Lock words: %zu requested, %zu pending across %zu region(s)\n",
               lock_words,
               pending_lock_words,
               pending_lock_regions);
        if (pending_lock_words > 0) {
            dump_lock_request_preview(payload.lock_bytes, payload.lock_size, lock_before);
        }
    }

    if (check_programmable_transition(current, payload.data_bytes, payload.data_size, &bad_offset) != 0) {
        fprintf(stderr,
                "[otp_provision] Refusing write: byte 0x%03zx would require a programmed bit to clear "
                "(current=0x%02x new=0x%02x)\n",
                bad_offset,
                current[bad_offset],
                payload.data_bytes[bad_offset]);
        goto out;
    }

    if (changed == 0 && pending_lock_words == 0) {
        printf("[otp_provision] OTP data and lock state already match the requested payload.\n");
        if (commit_write) {
            outcome = OTP_OUTCOME_SUCCESS;
        }
        ret = 0;
        goto out;
    }

    if (!commit_write) {
        printf("[otp_provision] Preview only. Re-run with --yes to program OTP.\n");
        ret = 0;
        goto out;
    }

    if (changed > 0) {
        if (apply_program_data(&dev,
                               current,
                               payload.data_bytes,
                               payload.data_size,
                               &written_words) != 0) {
            goto out;
        }

        printf("[otp_provision] OTP data write request completed (%zu word(s)).\n", written_words);
    }

    if (!skip_verify) {
        if (changed > 0) {
            bool data_unchanged = false;

            if (drv_pufs_otp_read(&dev, 0, verify, payload.data_size) != 0) {
                fprintf(stderr, "[otp_provision] Failed to read OTP for data verification\n");
                goto out;
            }

            if (verify_programmed_bytes(verify, current, payload.data_bytes, payload.data_size, &data_unchanged) != 0) {
                if (data_unchanged) {
                    fprintf(stderr,
                            "[otp_provision] OTP data did not change. The kernel is likely in PUFS dry-run mode; "
                            "enable RT_PUFS_OTP_WRITE_ENABLE to commit hardware writes.\n");
                    data_dry_run = true;
                } else {
                    fprintf(stderr, "[otp_provision] OTP data verification failed after write\n");
                    goto out;
                }
            } else {
                printf("[otp_provision] Data verification passed.\n");
            }
        }
    }

    if (pending_lock_words > 0) {
        if (apply_lock_requests(&dev, payload.lock_bytes, payload.lock_size, lock_before) != 0) {
            goto out;
        }

        printf("[otp_provision] OTP lock request completed.\n");
    }

    if (!skip_verify && lock_after) {
        if (snapshot_requested_lock_states(&dev, payload.lock_bytes, payload.lock_size, lock_after) != 0) {
            goto out;
        }

        if (verify_requested_locks(payload.lock_bytes, payload.lock_size, lock_after, &lock_mismatch_words) != 0) {
            if (pending_lock_words > 0 && memcmp(lock_before, lock_after, payload.lock_size / OTP_WORD_SIZE) == 0) {
                fprintf(stderr,
                        "[otp_provision] Lock state did not change. The kernel is likely in PUFS dry-run mode; "
                        "enable RT_PUFS_OTP_WRITE_ENABLE to commit hardware writes.\n");
                lock_dry_run = true;
            } else {
                fprintf(stderr,
                        "[otp_provision] Lock verification failed, %zu requested word(s) still not in the target state\n",
                        lock_mismatch_words);
                goto out;
            }
        } else if (lock_words > 0) {
            printf("[otp_provision] Lock verification passed.\n");
        }
    } else if (skip_verify) {
        printf("[otp_provision] Verification skipped by request.\n");
    }

    if (data_dry_run || lock_dry_run) {
        fprintf(stderr, "[otp_provision] Dry-run mode detected; requested OTP changes were not committed.\n");
        outcome = OTP_OUTCOME_DRY_RUN;
        ret = 1;
    } else {
        outcome = OTP_OUTCOME_SUCCESS;
        ret = 0;
    }

out:
    if (dev.fd >= 0) {
        drv_pufs_close(&dev);
    }

    if (commit_write) {
        printf("[otp_provision] Result: %s\n", otp_outcome_name(outcome));
        otp_status_led_signal(outcome);
    }

    free(current);
    free(verify);
    free(lock_before);
    free(lock_after);
    free(file_bytes);
    return ret;
}
